### ISSUE TITLE
Adding Branch Labels Auto-associates Project Board

### ISSUE THREAD

**Issue by mlaurencin** [electron/cation#91] opened 2022-02-17 22:09 UTC
Currently:

![image](https://user-images.githubusercontent.com/35157522/154548501-b2d22f6e-6475-4303-b026-b45ce60a6a5f.png)

What would be automatically done:

![image](https://user-images.githubusercontent.com/35157522/154579071-6c800cae-97a3-4bb8-a62d-f83c4ce0f82d.png)

@codebytere

**Comment by Jassi10000** [comment] 2022-03-15 11:16
@mlaurencin Are you currently working on this ?
Can you work with you too  ?

**Comment by codebytere** [comment] 2022-03-29 13:46
@Hanaffi sure! i can't assign you because you're not part of the Electron org, but you're welcome to work on it. I'm also happy to point you in the direction of the relevant API calls for this feature if you'd like.

**Comment by codebytere** [comment] 2022-03-29 21:00
@Hanaffi so, to elaborate here, we're trying to make it so that when a given issue is opened with a branch label (ex. `18-x-y`, `17-x-y`), the issue is automatically added as a new card to `Unsorted Issues` column of the project board with the same name ([board for `18-x-y`](https://github.com/orgs/electron/projects/40)).

So, you'd be using this call: https://octokit.github.io/rest.js/v18#projects-create-card

like so:

```js 
const {data: card} = await octokit.projects.createCard({
     column_id: column_id, // This is the id of the Unsorted Issues column, which you'l lneed to get
     content_id: content_id, // This is the issue number
     content_type: "Issue" // This will always be issue since we're associating an issue
})
```

**Comment by dsanders11** [comment] 2023-04-26 02:07
Closing this as we now accomplish this [using GitHub's project automation features](https://docs.github.com/en/issues/planning-and-tracking-with-projects/automating-your-project/adding-items-automatically).

**Closed by dsanders11** 2023-04-26 02:07 UTC
Labels: :sparkles: enhancement
